{
 "title": "Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Distribution of HTTP response codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(code) (rate(http_requests_received_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Services memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_private_memory_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}